//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistrationpageUsingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeedata
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> hobbiesid { get; set; }
    }
}
