//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistrationpageUsingMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEmployeeEntities : DbContext
    {
        public dbEmployeeEntities()
            : base("name=dbEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employeedata> Employeedatas { get; set; }
        public virtual DbSet<tblstate> tblstates { get; set; }
        public virtual DbSet<tblHoby> tblHobies { get; set; }
    
        public virtual ObjectResult<showalldata_Result> showalldata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showalldata_Result>("showalldata");
        }
    }
}
